version: '3'
services:
  jenkins:
    image: jenkinssqnet
    ports:
      - "8080:8080"
    networks:
      - my-network

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - my-network

networks:
  my-network:


